apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-nlgjqveg
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-nlgjqveg:11ce8fe3d2dfba4c4ea6e208bd561abb01058154@sha256:1ef624ffdb716932b306b7bf03a3d07f99fe760a8800a45f61412644bad45f47
          name: container-image
